# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages Ultimo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          command: npm run cypress:run
  generate-report:
    needs: cypress-tests
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install multiple-cucumber-html-reporter

      - name: Report
        run: node report.js

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet index.html; then
            echo "No changes detected in index.html"
            exit 0
          else
            echo "Changes detected in index.html"
            exit 1
          fi
      
      - name: Commit changes
        if: steps.check_changes.outcome == 'failure'
        run: |
          git config --global user.email "renato.sistemas@gmail.com"
          git config --global user.name "RenatoCabezasAntezana"
          git add .
          git commit -m "Update index.html"
      
      - name: Push changes
        if: steps.check_changes.outcome == 'failure'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      

  deploy:
    needs: generate-report
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "report"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
